name: Scheduled launch
on:
  schedule:
    - cron:  '30 12 * * *'

jobs:
  build:
    name: Launch
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        
      - name: Generate keys
        run: |
          cat > ./keys.json << EOF
          ${{ secrets.KEYS }}
          EOF
          
      - name: Generate fb json
        run: |
          cat > ./firebase.json << EOF
          ${{ secrets.FIREBASE }}
          EOF

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Launch jar
        run: |
          java -jar artifacts/whappens-1.0.jar days=7 prod=true
